tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-tertiary-fixed": "#400014",
                "error": "#ba1a1a",
                "on-error": "#ffffff",
                "on-secondary-fixed-variant": "#004b71",
                "surface-dim": "#cfdce4",
                "on-tertiary": "#ffffff",
                "on-secondary-container": "#00486c",
                "on-primary-fixed-variant": "#00429c",
                "surface-tint": "#2b5bb5",
                "surface-container-high": "#ddeaf2",
                "on-tertiary-container": "#ffa3b2",
                "primary-fixed-dim": "#b0c6ff",
                "surface-bright": "#f4faff",
                "on-background": "#111d23",
                "on-tertiary-fixed-variant": "#900038",
                "on-error-container": "#93000a",
                "inverse-primary": "#b0c6ff",
                "secondary-container": "#50b9ff",
                "secondary-fixed": "#cbe6ff",
                "secondary": "#006495",
                "on-primary-container": "#a1bbff",
                "tertiary-fixed-dim": "#ffb2be",
                "surface-container-low": "#e9f6fd",
                "outline": "#737783",
                "outline-variant": "#c3c6d4",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#001945",
                "secondary-fixed-dim": "#8fcdff",
                "on-surface-variant": "#434652",
                "on-surface": "#111d23",
                "primary": "#003178",
                "inverse-on-surface": "#e6f3fb",
                "tertiary": "#700029",
                "tertiary-container": "#9a003c",
                "surface-variant": "#d7e4ec",
                "inverse-surface": "#263238",
                "background": "#f4faff",
                "surface-container": "#e3f0f8",
                "surface": "#f4faff",
                "on-secondary-fixed": "#001e30",
                "on-primary": "#ffffff",
                "primary-container": "#0d47a1",
                "tertiary-fixed": "#ffd9de",
                "primary-fixed": "#d9e2ff",
                "on-secondary": "#ffffff",
                "surface-container-highest": "#d7e4ec"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "sm": "8px",
                "container-max": "1280px",
                "xs": "4px",
                "md": "16px",
                "xl": "48px",
                "gutter": "24px",
                "lg": "24px",
                "unit": "4px"
            },
            "fontFamily": {
                "display-xl": ["Work Sans"],
                "body-md": ["Inter"],
                "caption": ["Inter"],
                "body-lg": ["Inter"],
                "headline-md": ["Work Sans"],
                "headline-lg": ["Work Sans"],
                "label-bold": ["Inter"]
            },
            "fontSize": {
                "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "600"}],
                "label-bold": ["14px", {"lineHeight": "1", "fontWeight": "700"}]
            }
        },
    },
}
